project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - from-eukrhythmic.qmd

website:
  title: "MCR ciliates"
  sidebar:
    style: "docked"
    contents:
      - text: "Introduction"
        href: index.qmd
      - text: "Analysis"
      - section: "eukrhythmic"
        href: from-eukrhythmic.qmd
        

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    code-overflow: wrap
    code-line-numbers: true
    code-copy: true

editor: visual

