project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - about.qmd

website:
  title: "ciliate-mcr"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Initial data import

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

